name: Release

on:
  push:
    branches: [main]

concurrency:
  group: release
  cancel-in-progress: false

permissions:
  contents: write

jobs:
  lint:
    if: ${{ !startsWith(github.event.head_commit.message, 'chore(release):') }}
    uses: ./.github/workflows/lint.yml

  test:
    if: ${{ !startsWith(github.event.head_commit.message, 'chore(release):') }}
    uses: ./.github/workflows/test.yml

  bump:
    needs: [lint, test]
    uses: MaxiGarcia13/gh-actions/.github/workflows/bump-version.yml@main
    secrets: inherit
    with:
      # TODO: Remove release notes in this reusable workflow
      use_release_notes: false
      lfs: false

  deploy:
    needs: bump
    uses: ./.github/workflows/deploy.yml
    secrets: inherit

  release-notes:
    needs: bump
    uses: MaxiGarcia13/gh-actions/.github/workflows/create-release-notes.yml@main
    with:
      tag: ${{ needs.bump.outputs.tag }}
      default_branch: main
      notes_template: .github/RELEASE_NOTES.template.md
