name: Release workflow

on:
  push:
    branches: [main]

concurrency:
  group: release
  cancel-in-progress: false

permissions:
  contents: write

jobs:
  lint:
    if: ${{ !startsWith(github.event.head_commit.message, 'chore(release):') }}
    uses: ./.github/workflows/lint.yml

  test:
    if: ${{ !startsWith(github.event.head_commit.message, 'chore(release):') }}
    uses: ./.github/workflows/test.yml

  bump:
    needs: [lint, test]
    uses: MaxiGarcia13/gh-actions/.github/workflows/bump-version.yml@main
    secrets: inherit
    with:
      paths: |
        './src/**'
        './public/**'
        './tests/**'

  deploy:
    needs: bump
    uses: ./.github/workflows/deploy.yml
    secrets: inherit

  release-notes:
    if: ${{ needs.bump.outputs.tag != '' }}
    needs: bump
    uses: MaxiGarcia13/gh-actions/.github/workflows/create-release-notes.yml@main
    with:
      tag: ${{ needs.bump.outputs.tag }}
      default_branch: main
